# Lint workflow
#
# Ensures the code is formatted correctly.
# - On every push and PR, checks the code style conforms to the black format.
# - On every push and PR, checks the code is both PEP8 compliant and passes the
#   pyflakes error detector (both tests done with flake8). We use some flake8
#   plugins to check some extra things, such as docstring formatting.

name: lint

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: psf/black@20.8b1

  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('.gitub/workflows/lint.yaml') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 flake8-2020 flake8-bugbear flake8-comprehensions flake8-docstrings flake8-implicit-str-concat

      - name: Run flake8
        run: python -m flake8 . --docstring-convention numpy
