# pre-commit workflow
#
# Ensures the codebase passes the pre-commit stack, to catch in case developers
# don't have pre-commit set up locally.

name: pre-commit

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.0
